fix: `TransactionTransfer.AddHbarTransfer()`
hashgraph/hedera-sdk-go pull request #170
Opened 2021-06-10 01:33 UTC by danielakhterov

2021-06-10 02:08 UTC, xin-hedera requested changes
LGTM

the test failed because when parsing a `TransferTransaction` from marshaled bytes, the `hbarTransfers` map needs to be populated from the protobuf.

perhaps the same applies to `tokenIndexes`

2021-06-15 00:25 UTC, andrix10 commented on transfer_transaction.go
> +	transaction.setHbarTransfersOnProtobuf()
transaction.buildHbarTransfers() would be a better name for this in my opinion

2021-06-15 00:26 UTC, andrix10 approved these changes

2021-06-15 00:26 UTC, andrix10 commented on transfer_transaction.go
> +	transaction.setTokenTransfersOnProtobuf()
transaction.buildTokenTransfers() would be a better name for this in my opinion

2021-06-15 21:25 UTC, merged