Fix several issues
hashgraph/hedera-sdk-go pull request #193
Opened 2021-06-28 22:10 UTC by danielakhterov

Resolves: #191 
Resolves: #190 
Resolves: #189

2021-06-29 14:13 UTC, xin-hedera requested changes

2021-06-29 14:13 UTC, xin-hedera commented on topic_message_query.go
> +				handle.Unsubscribe()
this line is unreachable if:

1. unrecoverable error, thus on line 153, it breaks out the for loop
2. completion of the subscription, thus on line 157, it break out the for loop

2021-06-29 14:49 UTC, mehcode commented on topic_message_query.go
> +					message = make([]*mirror.ConsensusTopicResponse, resp.ChunkInfo.Total)
`make` is a bit weird coming from other low-level languages, but this will help @danielakhterov 

```go
make(TYPE, LENGTH, CAPACITY)
```

2021-06-29 15:17 UTC, xin-hedera commented
also `tokenID` is not set in fuction `tokenDeleteTransactionFromProtobuf`

2021-06-30 00:02 UTC, danielakhterov commented
@xin-hedera Created issue for your previous comment #199 Seems this was completely missed when doing entity ID checksums.

2021-06-30 13:57 UTC, xin-hedera approved these changes
LGTM

2021-06-30 20:23 UTC, merged