feat: added Client.SetTransportSecurity(bool)
hashgraph/hedera-sdk-go pull request #290
Opened 2021-09-29 03:15 UTC by andrix10

Signed-off-by: Andrei Kuzmiankov <andrei@launchbadge.com>

2021-09-29 05:04 UTC, danielakhterov requested changes

2021-09-29 05:04 UTC, danielakhterov commented on managed_node_address.go
> +func (address *ManagedNodeAddress) GetName() string {
Actually I'm not even sure if Go should have these getters/setters. However, if you decide to keep them make sure that they return `*string` not `string`.

2021-09-29 05:04 UTC, danielakhterov commented on managed_node_address.go
> +func (address *ManagedNodeAddress) ToString() string {
This should just be `String()` since it's Go

2021-09-29 05:04 UTC, danielakhterov commented on mirror_network.go
> +	networkNodes      map[*ManagedNodeAddress]*_MirrorNode
Should not use `*ManagedNodeAddress` as map key, use `string` instead. The key for `MirrorNetwork` should be the address, and the key for `Network` should be the serialized form of `AccountID`

2021-09-29 05:04 UTC, danielakhterov commented on mirror_node.go
> +func (node *_MirrorNode) ToSecure() *_MirrorNode {
Should be private.

2021-09-29 05:04 UTC, danielakhterov commented on network.go
> +	network                map[*ManagedNodeAddress]AccountID
Same case as `MirrorNetwork`

2021-09-29 05:04 UTC, danielakhterov commented on network.go
> +	transportSecurity      bool
Should add another field `verifyCertificates` like in Java

2021-09-29 05:04 UTC, danielakhterov commented on network.go
> +	temp := make(map[*ManagedNodeAddress]AccountID, len(net))
Don't set the second parameter on `make()` when constructing map.

2021-09-29 05:20 UTC, danielakhterov requested changes

2021-09-29 05:20 UTC, danielakhterov commented on mirror_network.go
> +	index             uint
This was removed from the Java SDK because this functionality is already achieved through the sorting of nodes.

2021-09-29 05:20 UTC, danielakhterov commented on network.go
> +		network:                make(map[*ManagedNodeAddress]AccountID),
The original value here was to keep a copy of the network the user submitted. This has been removed in Java SDK and instead a network map type will be constructed on the fly.

2021-09-29 06:03 UTC, andrix10 commented on managed_node_address.go
> +func (address *ManagedNodeAddress) IsInProcess() bool {
but maybe it will someday

2021-09-30 01:50 UTC, danielakhterov requested changes

2021-10-01 09:11 UTC, danielakhterov requested changes

2021-10-01 09:11 UTC, danielakhterov commented on network.go
> +				delete(network.managedNetwork.network, network.managedNetwork.nodes[i]._GetManagedNode().address._String())
```suggestion
				delete(network.managedNetwork.network, network.managedNetwork.nodes[i].accountID._String())
```

2021-10-01 09:11 UTC, danielakhterov commented on network.go
> +func (network *_Network) SetTransportSecurity(transportSecurity bool) *_Network {
Should be private.

2021-10-01 09:11 UTC, danielakhterov commented on network.go
> +func (network *_Network) SetVerifyCertificate(verify bool) *_Network {
Should be private

2021-10-01 09:11 UTC, danielakhterov commented on network.go
> +//func (network *_Network) Close() error {
Should uncomment?

2021-10-01 09:11 UTC, danielakhterov commented on nft_id.go
> +	if !id._IsZero() && client != nil && client.network._GetNetworkName() != nil {
```suggestion
	if !id._IsZero() && client != nil && client.GetNetworkName() != nil {
```

2021-10-01 09:11 UTC, danielakhterov commented on node.go
> +	managedNode       _ManagedNode
Same case as `_MirrorNode`

2021-10-01 09:11 UTC, danielakhterov commented on node.go
> +func (node _Node) _GetManagedNode() _ManagedNode {
```suggestion
func (node *_Node) _GetManagedNode() *_ManagedNode {
```

2021-10-01 09:11 UTC, danielakhterov commented on node.go
> +					println("skipping certificate check")
Should move this logging statement to outside the callback so it's not called each time the connection is established.

2021-10-01 09:11 UTC, danielakhterov commented on schedule_id.go
> +	if !id._IsZero() && client != nil && client.network._GetNetworkName() != nil {
```suggestion
	if !id._IsZero() && client != nil && client.GetNetworkName() != nil {
```

2021-10-01 09:11 UTC, danielakhterov commented on token_id.go
> +	if client.network._GetNetworkName() == nil {
```suggestion
	if client.GetNetworkName() == nil {
```

2021-10-01 09:11 UTC, danielakhterov commented on topic_id.go
> +	if !id._IsZero() && client != nil && client.network._GetNetworkName() != nil {
```suggestion
	if !id._IsZero() && client != nil && client.GetNetworkName() != nil {
```

2021-10-02 01:42 UTC, andrix10 commented on schedule_id.go
> +	if !id._IsZero() && client != nil && client.network._GetNetworkName() != nil {
`func (client *Client) GetNetworkName() NetworkName {
	return *client.network._GetNetworkName()
}`

currently its doesn't return a pointer, so i don't think its possible

2021-10-04 06:48 UTC, danielakhterov requested changes

2021-10-04 06:48 UTC, danielakhterov commented on managed_node_address.go
> +	hostAndPort := regexp.MustCompile(`(^.*):(\d+$)`)
Move to global space.

2021-10-04 06:48 UTC, danielakhterov commented on managed_network.go
> +	delete(network.network, node._GetAddress())
Not correct for `_Network`, but correct for `_MirrorNetwork`

2021-10-04 06:48 UTC, danielakhterov commented on mirror_node.go
> +	if node._ManagedNode.address != nil {
This should create a new node, not mute the current one.

2021-10-04 06:48 UTC, danielakhterov commented on network.go
> +	newNetwork := make(map[string]_IManagedNode, len(net))
Don't pass in a second parameter to make when constructing maps.

2021-10-04 06:48 UTC, danielakhterov commented on network.go
>  func (network *_Network) _GetNodeWaitTime() time.Duration {
Rename `NodeWaitTime` to `MinBackoff`

2021-10-04 06:48 UTC, danielakhterov commented on node.go
> +	if node._ManagedNode.address != nil {
Should return new node not mutate the current one.

2021-10-05 06:18 UTC, danielakhterov approved these changes

2021-10-29 21:20 UTC, danielakhterov approved these changes

2021-10-29 21:20 UTC, merged